steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/tp-docker-repo/app:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/tp-docker-repo/app:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - set
    - image
    - deployment/tp-cloud-app
    - app=europe-west1-docker.pkg.dev/$PROJECT_ID/tp-docker-repo/app:$SHORT_SHA
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=tp-gke-cluster'
